// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectWeb.Data;

#nullable disable

namespace ProjectWeb.Migrations
{
    [DbContext(typeof(ApplicationDB))]
    [Migration("20241216090351_ZborIDAutoIncrement")]
    partial class ZborIDAutoIncrement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjectWeb.Models.Entities.Checkin", b =>
                {
                    b.Property<int>("CheckinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CheckinID"));

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EsteValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("GreutateBagaj")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UtilizatorID")
                        .HasColumnType("int");

                    b.Property<int>("ZborID")
                        .HasColumnType("int");

                    b.HasKey("CheckinID");

                    b.HasIndex("UtilizatorID");

                    b.HasIndex("ZborID");

                    b.ToTable("Checkin");
                });

            modelBuilder.Entity("ProjectWeb.Models.Entities.Utilizator", b =>
                {
                    b.Property<int>("IdUtilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUtilizator"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nume")
                        .HasColumnType("longtext");

                    b.Property<string>("Parola")
                        .HasColumnType("longtext");

                    b.Property<bool>("Pasager")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdUtilizator");

                    b.ToTable("Utilizator");
                });

            modelBuilder.Entity("ProjectWeb.Models.Entities.Zbor", b =>
                {
                    b.Property<int>("IdZbor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdZbor"));

                    b.Property<DateTime?>("DataPlecare")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destinatie")
                        .HasColumnType("longtext");

                    b.Property<decimal>("GreutateMaximaBagaj")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Imbarcare")
                        .HasColumnType("longtext");

                    b.Property<int>("LocuriDisponibile")
                        .HasColumnType("int");

                    b.Property<string>("NumeCompanie")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("IdZbor");

                    b.ToTable("Zbor");
                });

            modelBuilder.Entity("ProjectWeb.Models.Entities.Checkin", b =>
                {
                    b.HasOne("ProjectWeb.Models.Entities.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWeb.Models.Entities.Zbor", "Zbor")
                        .WithMany()
                        .HasForeignKey("ZborID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");

                    b.Navigation("Zbor");
                });
#pragma warning restore 612, 618
        }
    }
}
